In [2]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.5.0


# Finding the positional maximum & minimum

In [3]:
# Create a new tensor for finding positional minimum & maximum
tf.random.set_seed(101)
myrand = tf.random.uniform(shape = [50])
myrand

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.47352195, 0.26436174, 0.01309514, 0.23674393, 0.4963869 ,
       0.7846708 , 0.9851632 , 0.70585525, 0.37917376, 0.22009254,
       0.71373796, 0.8803077 , 0.85996735, 0.39693463, 0.45731723,
       0.28909445, 0.90666807, 0.6278106 , 0.5868671 , 0.10963845,
       0.40782762, 0.8454608 , 0.96400416, 0.18488109, 0.38441122,
       0.56635725, 0.73927045, 0.89018357, 0.02526927, 0.603837  ,
       0.92137325, 0.55978   , 0.6534728 , 0.56656027, 0.99309516,
       0.77820945, 0.18306637, 0.5430728 , 0.00717652, 0.73795307,
       0.0427922 , 0.37531865, 0.36715972, 0.9051403 , 0.6278651 ,
       0.9789833 , 0.24429071, 0.81796324, 0.816332  , 0.44967985],
      dtype=float32)>

In [4]:
# Find the positional maximum
tf.argmax(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [5]:
# Index on our largest value position
myrand[34]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99309516>

In [6]:
tf.math.reduce_max(myrand)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99309516>

In [7]:
myrand[tf.argmax(myrand)] == tf.math.reduce_max(myrand)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [8]:
assert myrand[tf.argmax(myrand)] == tf.math.reduce_max(myrand)

In [9]:
# Finding the positional minimum
tf.argmin(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=38>

In [10]:
myrand[tf.argmin(myrand)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0071765184>

In [11]:
tf.math.reduce_min(myrand)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0071765184>