In [8]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.5.0


# Aggregating Tensors 

In [2]:

mytf = tf.constant([-1,-8])
mytf

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -8], dtype=int32)>

In [4]:
# Get the absolute values
tf.abs(mytf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 8], dtype=int32)>

* Minimum
* Maximum
* Mean
* Sum

In [9]:
# Creating a random tensor with values between 0 & 100 with 50 values
myrand = tf.constant(np.random.randint(0,100, size = 50))
myrand

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 44, 31, 47, 55, 59,  6, 17, 22, 12, 22, 52, 60, 97, 45, 91, 50,
       46, 65,  2, 78, 22, 63, 50, 70, 53, 32,  9, 54, 98, 26, 45, 45, 20,
       23, 90, 11, 94, 44, 71, 28, 72,  1, 11, 81, 13, 88, 20, 84, 41])>

In [10]:
tf.size(myrand), myrand.ndim, myrand.dtype, myrand.shape 

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, tf.int64, TensorShape([50]))

In [11]:
# Minimum value
tf.reduce_min(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [12]:
# Maximum Value
tf.reduce_max(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [13]:
# Mean Value
tf.reduce_mean(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [15]:
# Sum
tf.reduce_sum(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=2356>

In [19]:
import tensorflow_probability as tfp

In [21]:
# variance
tfp.stats.variance(myrand)

<tf.Tensor: shape=(), dtype=int64, numpy=797>

In [28]:
tf.math.reduce_variance(tf.cast(myrand, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=797.50555>

In [25]:
# Standard Deviaiton
tf.math.reduce_std(tf.cast(myrand, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.24014>