In [1]:
# Importing Tensorflow
import tensorflow as tf
print(tf.__version__)
import numpy as np

2.5.0


# Squaring, Log, Square Root

In [2]:
mytf = tf.range(1,10)
mytf

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [3]:
tf.square(mytf)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [7]:
# tf.sqrt(mytf)
# Method has to be float

In [8]:
# Method requires float dtypes
tf.sqrt(tf.cast(mytf, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [10]:
# Log
tf.math.log(tf.cast(mytf, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>