In [22]:
import tensorflow as tf
print(tf.__version__)

2.5.0


- Introduction to Tensors
- Getting information from Tensors
- Manipulating Tensors
- Tensors & NumPy
- Using @t.funciton - To speed-up regular python functions
- Using GPUs or TPUs with TensorFlow
- Assignments

In [7]:
# Creating a tensorflow unchangeable constant - constant
my_tf1 = tf.constant(9)
print(my_tf1)
my_tf1

tf.Tensor(9, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [8]:
# Creating a tensorflow unchangeable constant - 1 D or Venctor
my_tf1d = tf.constant([9,8,1,2])
print(my_tf1d)
my_tf1d

tf.Tensor([9 8 1 2], shape=(4,), dtype=int32)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 8, 1, 2])>

In [9]:
# Creating a tensorflow unchangeable constant - constant - 2 D 
my_tf2d = tf.constant([[1,2],[3,4]])
print(my_tf2d)
my_tf2d

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [10]:
# Creating a variable
my_tf_var = tf.Variable([10,20,30])
print(my_tf_var)
my_tf_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30])>


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30])>

In [12]:
my_tf1d[0].assign(99)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [15]:
my_tf_var[0].assign(99)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([99, 20, 30])>

In [16]:
my_tf_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([99, 20, 30])>

In [18]:
my_tf_var.dtype

tf.int32

In [19]:
my_tf2d.ndim

2

In [20]:
my_tf2d.shape

TensorShape([2, 2])

In [21]:
my_tf_var.shape

TensorShape([3])

In [23]:
# Creating a tensorflow constant 
constf = tf.constant([1,2,3,4,5], dtype=tf.float32)

In [24]:
constf

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [25]:
constf.ndim

1

In [26]:
constf.dtype

tf.float32

In [27]:
constf.shape

TensorShape([5])

In [46]:
# Creating a tensorlfow variable
vartf = tf.Variable(['a','b','c','d','e'], dtype = tf.string)

In [34]:
vartf

<tf.Variable 'Variable:0' shape=(5,) dtype=string, numpy=array([b'a', b'b', b'c', b'd', b'e'], dtype=object)>

In [35]:
print(vartf)

<tf.Variable 'Variable:0' shape=(5,) dtype=string, numpy=array([b'a', b'b', b'c', b'd', b'e'], dtype=object)>


In [37]:
vartf.shape

TensorShape([5])

In [38]:
vartf.dtype

tf.string

In [40]:
vartf.value()

<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'a', b'b', b'c', b'd', b'e'], dtype=object)>

In [42]:
vartf.numpy()

array([b'a', b'b', b'c', b'd', b'e'], dtype=object)

In [48]:
# Assigning or updating variable
vartf = tf.Variable([1,2,3], dtype = tf.int32)

In [49]:
vartf[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [50]:
vartf[0].assign(100)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([100,   2,   3])>

In [51]:
vartf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100,   2,   3])>

# Random Tensors

In [53]:
rand1 = tf.random.normal([3,3])

In [54]:
rand1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.15007879, -1.1479646 , -0.95872945],
       [-0.3391757 , -0.26348972,  0.08205052],
       [-0.12499978, -0.10525679, -1.2089556 ]], dtype=float32)>

In [55]:
rand1.ndim

2

In [56]:
rand1.shape

TensorShape([3, 3])

In [59]:
rand_seed = tf.random.Generator.from_seed(101)

In [65]:
rand_seed = tf.random.Generator.from_seed(101)
rand_seed.normal([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.08036723, -1.7199678 , -0.6891769 ,  0.22862972],
       [-0.69891334, -0.11101238, -0.44537356,  0.1335287 ],
       [ 0.12417295,  0.96785086, -0.35425642, -0.8899504 ],
       [ 0.6247422 , -0.7167875 ,  1.2657576 , -0.04759569]],
      dtype=float32)>

In [61]:
rand_seed.normal((5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.19140726, -0.3555461 ,  1.5696619 ,  0.20746839,  0.20725876],
       [ 0.3713521 ,  0.19519211, -0.82391924, -0.60942024,  0.43897796],
       [-0.1458506 , -0.80299944,  0.06389246, -1.520157  , -0.15557258],
       [ 0.9957395 ,  1.0129821 ,  2.0632813 ,  0.86751133, -1.2219292 ],
       [ 0.37480515, -0.02102797,  0.9785194 ,  0.27187097,  1.5302081 ]],
      dtype=float32)>

# Turning Numpy Array into Tensors

In [66]:
numpy01 = np.arange(1,25,dtype = np.int32)

In [67]:
numpy01

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [68]:
numpy_tf = tf.constant(numpy01)

In [69]:
numpy_tf

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

# Getting info from Tensors

*   Shape
*   Rank - Means Dimensions
*   Axis or Dimensions
*   Size

In [74]:
mytf = tf.random.normal((5,5))
mytf
#tf.round(mytf,2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.5266268 , -0.91323966,  1.7929833 , -1.2123812 , -0.08350507],
       [ 0.57909673, -0.93995786, -0.1343091 ,  1.2543613 ,  0.19756953],
       [-2.746631  , -0.19550392, -0.26244   , -0.61866   , -0.85656   ],
       [-1.4644089 ,  2.1609333 ,  0.52584565, -0.27211696, -0.32936555],
       [-0.94879425,  0.97819895,  0.35098058,  0.75247604, -2.446671  ]],
      dtype=float32)>

In [81]:
mytf1=np.round(mytf,2)

In [82]:
mytf1

array([[ 0.53, -0.91,  1.79, -1.21, -0.08],
       [ 0.58, -0.94, -0.13,  1.25,  0.2 ],
       [-2.75, -0.2 , -0.26, -0.62, -0.86],
       [-1.46,  2.16,  0.53, -0.27, -0.33],
       [-0.95,  0.98,  0.35,  0.75, -2.45]], dtype=float32)

In [83]:
mytf1.shape

(5, 5)

In [84]:
mytf1.ndim

2

In [85]:
tf.size(mytf1)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [86]:
# Getting various attributes of Tensors
print('Datatype of every elemets: ', mytf1.dtype)
print('Number of Dimensions (Rank): ', mytf1.ndim)
print('Shape of tensor: ', mytf1.shape)
print('Elements along the 0 axis: ', mytf1.shape[0])
print('Elements along the last axis: ', mytf1.shape[-1])
print('Total number of elements in the tensor: ', tf.size(mytf1))
print('Total number of elements in the tensor: ', tf.size(mytf1).numpy())

Datatype of every elemets:  float32
Number of Dimensions (Rank):  2
Shape of tensor:  (5, 5)
Elements along the 0 axis:  5
Elements along the last axis:  5
Total number of elements in the tensor:  tf.Tensor(25, shape=(), dtype=int32)
Total number of elements in the tensor:  25


# Indexing Tensors

In [108]:
mytf = tf.random.uniform(shape = (2,3,4,5), minval=0, maxval=5, dtype = tf.dtypes.int32)
mytf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 1, 0, 2],
         [2, 4, 1, 1, 4],
         [3, 0, 1, 1, 2],
         [2, 1, 2, 2, 1]],

        [[3, 2, 0, 2, 0],
         [3, 1, 0, 3, 3],
         [0, 0, 0, 0, 4],
         [4, 4, 3, 3, 2]],

        [[3, 0, 4, 1, 0],
         [3, 2, 1, 1, 1],
         [0, 0, 2, 0, 2],
         [2, 3, 4, 1, 1]]],


       [[[3, 0, 4, 3, 1],
         [3, 2, 3, 3, 0],
         [0, 3, 4, 3, 4],
         [3, 1, 0, 0, 1]],

        [[4, 1, 0, 4, 3],
         [2, 0, 4, 4, 0],
         [1, 0, 1, 3, 3],
         [4, 0, 1, 1, 1]],

        [[1, 2, 4, 4, 0],
         [0, 0, 1, 3, 3],
         [1, 1, 3, 4, 4],
         [1, 3, 1, 1, 4]]]])>

In [109]:
#myz = tf.zeros([2,3,4,5])
#myz

In [110]:
mytf[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[0, 0, 1, 0, 2],
        [2, 4, 1, 1, 4],
        [3, 0, 1, 1, 2],
        [2, 1, 2, 2, 1]],

       [[3, 2, 0, 2, 0],
        [3, 1, 0, 3, 3],
        [0, 0, 0, 0, 4],
        [4, 4, 3, 3, 2]],

       [[3, 0, 4, 1, 0],
        [3, 2, 1, 1, 1],
        [0, 0, 2, 0, 2],
        [2, 3, 4, 1, 1]]])>

In [111]:
mytf[0][0]

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[0, 0, 1, 0, 2],
       [2, 4, 1, 1, 4],
       [3, 0, 1, 1, 2],
       [2, 1, 2, 2, 1]])>

In [113]:
mytf[0][0][:3,:2]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [2, 4],
       [3, 0]])>

In [117]:
# Getting 1st two elements of each dimensions
#rank_4_tensor[:2,:2,:2,:2]
mytf[:,:,:3,:2]

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[0, 0],
         [2, 4],
         [3, 0]],

        [[3, 2],
         [3, 1],
         [0, 0]],

        [[3, 0],
         [3, 2],
         [0, 0]]],


       [[[3, 0],
         [3, 2],
         [0, 3]],

        [[4, 1],
         [2, 0],
         [1, 0]],

        [[1, 2],
         [0, 0],
         [1, 1]]]])>

In [120]:
mytf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 1, 0, 2],
         [2, 4, 1, 1, 4],
         [3, 0, 1, 1, 2],
         [2, 1, 2, 2, 1]],

        [[3, 2, 0, 2, 0],
         [3, 1, 0, 3, 3],
         [0, 0, 0, 0, 4],
         [4, 4, 3, 3, 2]],

        [[3, 0, 4, 1, 0],
         [3, 2, 1, 1, 1],
         [0, 0, 2, 0, 2],
         [2, 3, 4, 1, 1]]],


       [[[3, 0, 4, 3, 1],
         [3, 2, 3, 3, 0],
         [0, 3, 4, 3, 4],
         [3, 1, 0, 0, 1]],

        [[4, 1, 0, 4, 3],
         [2, 0, 4, 4, 0],
         [1, 0, 1, 3, 3],
         [4, 0, 1, 1, 1]],

        [[1, 2, 4, 4, 0],
         [0, 0, 1, 3, 3],
         [1, 1, 3, 4, 4],
         [1, 3, 1, 1, 4]]]])>

In [121]:
mytf[0:2]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 1, 0, 2],
         [2, 4, 1, 1, 4],
         [3, 0, 1, 1, 2],
         [2, 1, 2, 2, 1]],

        [[3, 2, 0, 2, 0],
         [3, 1, 0, 3, 3],
         [0, 0, 0, 0, 4],
         [4, 4, 3, 3, 2]],

        [[3, 0, 4, 1, 0],
         [3, 2, 1, 1, 1],
         [0, 0, 2, 0, 2],
         [2, 3, 4, 1, 1]]],


       [[[3, 0, 4, 3, 1],
         [3, 2, 3, 3, 0],
         [0, 3, 4, 3, 4],
         [3, 1, 0, 0, 1]],

        [[4, 1, 0, 4, 3],
         [2, 0, 4, 4, 0],
         [1, 0, 1, 3, 3],
         [4, 0, 1, 1, 1]],

        [[1, 2, 4, 4, 0],
         [0, 0, 1, 3, 3],
         [1, 1, 3, 4, 4],
         [1, 3, 1, 1, 4]]]])>

In [151]:
#mytf[:2,][:2][:2,][:2,]

In [138]:
mytf[:2,:2,:,:]

<tf.Tensor: shape=(2, 2, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 1, 0, 2],
         [2, 4, 1, 1, 4],
         [3, 0, 1, 1, 2],
         [2, 1, 2, 2, 1]],

        [[3, 2, 0, 2, 0],
         [3, 1, 0, 3, 3],
         [0, 0, 0, 0, 4],
         [4, 4, 3, 3, 2]]],


       [[[3, 0, 4, 3, 1],
         [3, 2, 3, 3, 0],
         [0, 3, 4, 3, 4],
         [3, 1, 0, 0, 1]],

        [[4, 1, 0, 4, 3],
         [2, 0, 4, 4, 0],
         [1, 0, 1, 3, 3],
         [4, 0, 1, 1, 1]]]])>

In [152]:
mytf[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [2, 4]],

        [[3, 2],
         [3, 1]]],


       [[[3, 0],
         [3, 2]],

        [[4, 1],
         [2, 0]]]])>

In [154]:
mytf[1,2,3]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 1, 1, 4])>

In [155]:
mytf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 1, 0, 2],
         [2, 4, 1, 1, 4],
         [3, 0, 1, 1, 2],
         [2, 1, 2, 2, 1]],

        [[3, 2, 0, 2, 0],
         [3, 1, 0, 3, 3],
         [0, 0, 0, 0, 4],
         [4, 4, 3, 3, 2]],

        [[3, 0, 4, 1, 0],
         [3, 2, 1, 1, 1],
         [0, 0, 2, 0, 2],
         [2, 3, 4, 1, 1]]],


       [[[3, 0, 4, 3, 1],
         [3, 2, 3, 3, 0],
         [0, 3, 4, 3, 4],
         [3, 1, 0, 0, 1]],

        [[4, 1, 0, 4, 3],
         [2, 0, 4, 4, 0],
         [1, 0, 1, 3, 3],
         [4, 0, 1, 1, 1]],

        [[1, 2, 4, 4, 0],
         [0, 0, 1, 3, 3],
         [1, 1, 3, 4, 4],
         [1, 3, 1, 1, 4]]]])>

In [159]:
mytf[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=int32, numpy=array([[[[0]]]])>

In [161]:
mytf[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 1, 0, 2]]]])>

In [162]:
mytf[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 1, 0, 2]]]])>

In [163]:
mytf.shape

TensorShape([2, 3, 4, 5])

In [164]:
mytf.ndim

4

# Adding extra dimension - 
- Without loosing or adding the extra information

In [166]:
# ... meand on every previous axis
mytf[...,tf.newaxis]

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=int32, numpy=
array([[[[[0],
          [0],
          [1],
          [0],
          [2]],

         [[2],
          [4],
          [1],
          [1],
          [4]],

         [[3],
          [0],
          [1],
          [1],
          [2]],

         [[2],
          [1],
          [2],
          [2],
          [1]]],


        [[[3],
          [2],
          [0],
          [2],
          [0]],

         [[3],
          [1],
          [0],
          [3],
          [3]],

         [[0],
          [0],
          [0],
          [0],
          [4]],

         [[4],
          [4],
          [3],
          [3],
          [2]]],


        [[[3],
          [0],
          [4],
          [1],
          [0]],

         [[3],
          [2],
          [1],
          [1],
          [1]],

         [[0],
          [0],
          [2],
          [0],
          [2]],

         [[2],
          [3],
          [4],
          [1],
          [1]]]],



       [[[[3]

In [174]:
mytf[:,:,:,:,tf.newaxis]

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=int32, numpy=
array([[[[[0],
          [0],
          [1],
          [0],
          [2]],

         [[2],
          [4],
          [1],
          [1],
          [4]],

         [[3],
          [0],
          [1],
          [1],
          [2]],

         [[2],
          [1],
          [2],
          [2],
          [1]]],


        [[[3],
          [2],
          [0],
          [2],
          [0]],

         [[3],
          [1],
          [0],
          [3],
          [3]],

         [[0],
          [0],
          [0],
          [0],
          [4]],

         [[4],
          [4],
          [3],
          [3],
          [2]]],


        [[[3],
          [0],
          [4],
          [1],
          [0]],

         [[3],
          [2],
          [1],
          [1],
          [1]],

         [[0],
          [0],
          [2],
          [0],
          [2]],

         [[2],
          [3],
          [4],
          [1],
          [1]]]],



       [[[[3]

# Alternative to tf.newaxis

In [175]:
# Expanding on the final axis
tf.expand_dims(mytf, axis = -1)

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=int32, numpy=
array([[[[[0],
          [0],
          [1],
          [0],
          [2]],

         [[2],
          [4],
          [1],
          [1],
          [4]],

         [[3],
          [0],
          [1],
          [1],
          [2]],

         [[2],
          [1],
          [2],
          [2],
          [1]]],


        [[[3],
          [2],
          [0],
          [2],
          [0]],

         [[3],
          [1],
          [0],
          [3],
          [3]],

         [[0],
          [0],
          [0],
          [0],
          [4]],

         [[4],
          [4],
          [3],
          [3],
          [2]]],


        [[[3],
          [0],
          [4],
          [1],
          [0]],

         [[3],
          [2],
          [1],
          [1],
          [1]],

         [[0],
          [0],
          [2],
          [0],
          [2]],

         [[2],
          [3],
          [4],
          [1],
          [1]]]],



       [[[[3]

In [176]:
# Adding extra dimension at teh front
tf.expand_dims(mytf, axis = 0)

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=int32, numpy=
array([[[[[0, 0, 1, 0, 2],
          [2, 4, 1, 1, 4],
          [3, 0, 1, 1, 2],
          [2, 1, 2, 2, 1]],

         [[3, 2, 0, 2, 0],
          [3, 1, 0, 3, 3],
          [0, 0, 0, 0, 4],
          [4, 4, 3, 3, 2]],

         [[3, 0, 4, 1, 0],
          [3, 2, 1, 1, 1],
          [0, 0, 2, 0, 2],
          [2, 3, 4, 1, 1]]],


        [[[3, 0, 4, 3, 1],
          [3, 2, 3, 3, 0],
          [0, 3, 4, 3, 4],
          [3, 1, 0, 0, 1]],

         [[4, 1, 0, 4, 3],
          [2, 0, 4, 4, 0],
          [1, 0, 1, 3, 3],
          [4, 0, 1, 1, 1]],

         [[1, 2, 4, 4, 0],
          [0, 0, 1, 3, 3],
          [1, 1, 3, 4, 4],
          [1, 3, 1, 1, 4]]]]])>